# Generated by Django 5.0.3 on 2024-05-01 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answerlike',
            unique_together={('author', 'answer')},
        ),
        migrations.AlterUniqueTogether(
            name='questionlike',
            unique_together={('author', 'question')},
        ),
    ]
